### ISSUE TITLE
Lag spikes entering and leaving regions.

### ISSUE THREAD

**Issue by ChefKillz4Thrillz** [Trojaner25/Rocket-Regions#69] opened 2017-01-11 02:41 UTC
Massive lag spikes whenever entering and leaving a region area, sometimes resulting in player crashing out. Re-installed plugin, re-installed bundles, restarted server. Error in log reads:

[1/10/2017 6:06:14 PM] [Error] Error in MulticastDelegate PlayerUpdatePosition: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Can't cast Int32 to UInt16
  at RocketRegions.Model.Flag.RegionFlag.GetValue[UInt16] (Group group) [0x00000] in <filename unknown>:0 
  at RocketRegions.Model.Flag.Impl.LeaveEffectFlag.OnRegionLeave (Rocket.Unturned.Player.UnturnedPlayer player) [0x00000] in <filename unknown>:0 
  at RocketRegions.RegionsPlugin.OnPlayerLeftRegion (IRocketPlayer player, RocketRegions.Model.Region region) [0x00000] in <filename unknown>:0 
  at RocketRegions.RegionsPlugin.OnPlayerUpdatePosition (IRocketPlayer player, Vector3 position) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <filename unknown>:0 
  at Rocket.Core.Extensions.MulticastDelegateExtension.TryInvoke (System.MulticastDelegate theDelegate, System.Object[] args) [0x00000] in <filename unknown>:0 

Plz Helpz

**Comment by Trojaner** [comment] 2017-04-15 12:25
Remove Enter/Leave effects, duplicate of #70

**Closed as completed by Trojaner** 2017-04-15 12:25 UTC
Labels: bug, duplicate, confirmed
